name: Main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install package
        run: |
          npm install -g @angular/cli@17
          npm ci
      - name: run tests
        run: |
          ./run-tests.sh

        env:
          CI: true
